/* DOM identity regressions: updates must preserve controls and inspected rows. */
const {parseHTML}=require('../.test-deps/node_modules/linkedom');
const fs=require('node:fs');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const {document,window}=parseHTML('<html><body></body></html>');
// linkedom exposes select.value as read-only; emulate the native setter.
const selectValue=Object.getOwnPropertyDescriptor(window.HTMLSelectElement.prototype,'value');
Object.defineProperty(window.HTMLSelectElement.prototype,'value',{get:selectValue.get,set(value){for(const option of this.querySelectorAll('option')) option.selected=option.value===value;}});
Object.defineProperty(Object.getPrototypeOf(document.createElement('details')),'open',{get(){return this.hasAttribute('open');},set(value){if(value)this.setAttribute('open','');else this.removeAttribute('open');},configurable:true});
let timer;
vm.runInNewContext(fs.readFileSync('custom_components/ha_security/www/ha-security-card.js','utf8'),{
  HTMLElement:window.HTMLElement,customElements:window.customElements,window,
  setInterval:fn=>{timer=fn;return 1;},clearInterval:()=>{},CustomEvent:window.CustomEvent,
});
const card=document.createElement('ha-security-card');document.body.appendChild(card);card.setConfig({});
const row=(id,state='connected')=>({session_id:id,token_id:'token',user_id:'u',user_name:'Matt',label:'Browser',state,first_observed_at:'2026-10-10T12:00:00Z'});
let revision=0;
const update=(active,ended=[],count=active.length)=>{
 const entities=[
 ['overview',{tracking_status:'observing',connected_websockets:count}],
 ['refresh_tokens',{user_id:'u',user_name:'Matt'}],
 ['active_websocket_connections',{user_id:'u',active_connections:active,session_history:ended}],
 ['recently_used_tokens',{user_id:'u',connections:[{token_id:'token',user_id:'u',label:'Browser',token_type:'normal'}]}],
 ];
 card.hass={states:Object.fromEntries(entities.map(([metric,attributes])=>[metric,{entity_id:metric,state:'1',last_updated:String(++revision),attributes:{ha_security_metric:metric,...attributes}}]))};
};
update([row('a')]);
const root=card.shadowRoot;
const inspected=root.querySelector('details[data-id="a"]');inspected.open=true;
const selector=root.querySelector('[data-select-user]');
// Simulate native focus: linkedom doesn't implement browser focus/popovers.
Object.defineProperty(root,'activeElement',{configurable:true,value:selector});
const options=[...selector.children];
update([row('new'),{...row('a'),last_seen_at:'2026-10-10T13:00:00Z'}],[],2);
assert.equal(root.querySelector('details[data-id="a"]'),inspected);
assert.ok(inspected.open);
assert.equal(root.querySelector('[data-select-user]'),selector);
assert.deepEqual([...selector.children],options);
assert.ok(root.querySelector('.stats strong').textContent.includes('2'));
assert.equal(root.querySelector('.list details').dataset.id,'a'); // arrival appended while inspecting
assert.ok(root.querySelector('details[data-id="new"]'));
update([row('new')],[{...row('a','closed'),closed_at:'2026-10-10T14:00:00Z'}]);
assert.equal(root.querySelector('details[data-id="a"]'),inspected);
assert.ok(inspected.open);
assert.ok(inspected.textContent.includes('closed'));
assert.ok(inspected.textContent.includes('This connection disconnected'));
inspected.open=false;update([row('new')]);
assert.equal(root.querySelector('details[data-id="a"]'),null);
// Counts keep updating even while a different control is being used.
for(const tab of ['history','credentials','logins','activity']){
 card.tab=tab;card.render();
 const select=root.querySelector('[data-select-user]');
 Object.defineProperty(root,'activeElement',{configurable:true,value:select});
 update([row('new')],[],7);
 assert.equal(root.querySelector('[data-select-user]'),select);
 assert.equal(card.tab,tab);
 assert.equal(root.querySelector('.stats strong').textContent,'7');
}
Object.defineProperty(root,'activeElement',{configurable:true,value:null});
card.tab='activity';card.activityResult={records:[{id:'event',kind:'websocket_action',user_name:'Matt',token_id:'token',session_id:'a',domain:'light',service:'turn_on'}],total:1};card.render();
const event=root.querySelector('[data-id="activity-event"]');event.open=true;
const raw=root.querySelector('[data-id="activity-event-raw"]');raw.open=true;
card.activityResult.records[0].invocation_observed=true;card.render(true);
assert.equal(root.querySelector('[data-id="activity-event"]'),event);
assert.equal(root.querySelector('[data-id="activity-event-raw"]'),raw);
assert.ok(raw.open && event.open);
assert.ok(event.textContent.includes('Service invocation observed'));
card.disconnectedCallback();
console.log('DOM identity, live counts, dropdown preservation, arrival ordering, closed connection and nested expansion checks passed');
// Use responses generated by the real Python inventory/tracker/admin action handlers.
(async()=>{
 const fixture=JSON.parse(fs.readFileSync('.test-deps/activity-contract.json','utf8'));
 const attributes=(metric,extra)=>({entity_id:metric,state:'1',last_updated:'contract',attributes:{ha_security_metric:metric,...extra}});
 const source=[attributes('overview',{tracking_status:'observing'}),attributes('refresh_tokens',{user_id:fixture.user_id,user_name:'Matt'}),attributes('active_websocket_connections',{...fixture.view,user_id:fixture.user_id})];
 let requests=[];
 const callWS=async request=>{
   requests.push(request);
   assert.equal(request.service_data.token_id,fixture.token_id);
   assert.equal(request.service_data.user_id,fixture.user_id);
   assert.equal(request.service_data.since,undefined);
   assert.equal(request.service_data.until,undefined);
   return {response:request.service==='query_sessions' ? fixture.connections : request.service_data.category==='actions' ? fixture.actions : fixture.inventory};
 };
 card.tab='live';card.user='all';card.query='';card.filter='all';
 card.hass={states:Object.fromEntries(source.map(e=>[e.entity_id,e])),callWS};
 card.render();
 const selected=fixture.connections.sessions[0];
 const related=root.querySelector(`[data-related="${fixture.token_id}"][data-session="${selected.session_id}"]`);
 assert.ok(related,'Real live row must carry its authenticated credential and session IDs');
 card.since='2000-01-01T00:00';card.until='2000-01-02T00:00';
 related.onclick();await new Promise(resolve=>setImmediate(resolve));
 assert.equal(requests[0].service_data.category,'actions');
 assert.ok(root.innerHTML.includes('Matt submitted light.turn_on'));
 assert.ok(root.innerHTML.includes('light.kitchen'));
 assert.ok(root.innerHTML.includes('Credential match: Found'));
 assert.ok(!root.innerHTML.includes('lock.unlock'));
 root.querySelector('[data-mode="direct"]').onclick();await new Promise(resolve=>setImmediate(resolve));
 assert.equal(requests.at(-1).service_data.category,'inventory');
 assert.ok(root.innerHTML.includes('Existing credential first observed'));
 assert.ok(!root.innerHTML.includes('Matt submitted light.turn_on'));
 assert.ok(!root.innerHTML.includes('light.kitchen'));
 root.querySelector('[data-mode="connections"]').onclick();await new Promise(resolve=>setImmediate(resolve));
 assert.ok(root.innerHTML.includes(selected.session_id));
 assert.ok(root.innerHTML.includes('WebSocket connection connected'));
 const before=requests.length;
 await card.openRelated({related:'',owner:fixture.user_id,session:'missing-id'});
 assert.equal(requests.length,before,'Missing credential must not broaden the request to all credentials');
 assert.ok(root.innerHTML.includes('no captured credential ID'));
 card.related={token_id:fixture.token_id,user_id:fixture.user_id};
 assert.ok(card.activityEmpty({records:[]}).includes('matching integration and dashboard'));
 assert.ok(card.activityEmpty({activity_api_version:2,credential_scope:{known:false}}).includes('unmatched credential'));
 card.activityMode='actions';
 assert.ok(card.activityEmpty({activity_api_version:2,websocket_action_status:'disabled'}).includes('not observing'));

 card.related=null;card.activityUser="";card.user="all";
 card.credentialOptions=[{token_id:"agent",user_id:"u",user_name:"Matt",label:"HASS.Agent",token_type:"long_lived_access_token"},{token_id:"refresh",user_id:"v",user_name:"Other",label:"Phone",token_type:"normal"}];
 card.activityResult={records:[],total:0};card.render();
 assert.equal(root.querySelectorAll('[data-credential-choice]').length,2);
 const dropdown=root.querySelector('[data-id="credential-filter"]');dropdown.open=true;
 assert.ok(dropdown.getAttribute('style').includes('overflow:visible'));
 assert.ok(root.querySelector('style').textContent.includes('ha-card{overflow:visible'));
 card.loadActivity=async()=>{};
 const agent=root.querySelector('[data-credential-choice="agent"]');agent.checked=false;agent.onchange();card.render(true);
 assert.ok(card.hiddenCredentials.has('agent'));assert.equal(root.querySelector('[data-id="credential-filter"]'),dropdown);assert.ok(dropdown.open);
 card.activityUser="u";card.render();assert.equal(root.querySelectorAll('[data-credential-choice]').length,1);
 assert.ok(root.innerHTML.includes('HASS.Agent'));
 root.querySelector('[data-show-credentials]').onclick();assert.equal(card.hiddenCredentials.size,0);

 const filterCard=document.createElement('ha-security-card');document.body.appendChild(filterCard);filterCard.setConfig({});
 filterCard.tab='activity';filterCard.activityMode='actions';
 const choices=[{token_id:'agent',user_id:'u',user_name:'Matt',label:'HASS.Agent',token_type:'long_lived_access_token'},{token_id:'phone',user_id:'u',user_name:'Matt',label:'Phone',token_type:'normal'}];
 const activity=[{id:'agent-read',kind:'rest_request',token_id:'agent',user_id:'u',user_name:'Matt',request_label:'Agent states',http_status:200},{id:'phone-read',kind:'rest_request',token_id:'phone',user_id:'u',user_name:'Matt',request_label:'Phone states',http_status:200}];
 let lastFilter;
 filterCard.hass={states:{},callWS:async request=>{lastFilter=request.service_data;const records=activity.filter(r=>!request.service_data.exclude_token_ids.includes(r.token_id));return {response:{records,total:records.length,credential_options:choices,activity_api_version:2}};}};
 await filterCard.loadActivity(0);
 const filterRoot=filterCard.shadowRoot;
 const controls=filterRoot.querySelector('.activity-filters');
 assert.ok(controls.querySelector('.date-filters [data-date="since"]'));
 assert.ok(controls.querySelector('.date-filters [data-date="until"]'));
 assert.ok(controls.querySelector('.identity-filters [data-activity-user]'));
 assert.ok(controls.querySelector('.identity-filters [data-id="credential-filter"]'));
 const popup=filterRoot.querySelector('[data-id="credential-filter"]');popup.open=true;
 window.innerWidth=400;window.innerHeight=800;
 popup.querySelector('summary').getBoundingClientRect=()=>({right:390,top:260,bottom:300});
 filterCard.positionCredentialMenu();
 const popupMenu=popup.querySelector('[role="group"]');
 assert.equal(popupMenu.style.position,'fixed');
 assert.ok(parseFloat(popupMenu.style.left)>=16);
 assert.ok(parseFloat(popupMenu.style.left)+parseFloat(popupMenu.style.width)<=384);
 window.innerWidth=1200;filterCard.positionCredentialMenu();assert.equal(popupMenu.style.width,'560px');
 filterRoot.querySelector('[data-id="activity-agent-read"]').open=true;
 const agentChoice=filterRoot.querySelector('[data-credential-choice="agent"]');agentChoice.checked=false;agentChoice.dispatchEvent(new window.Event('change'));
 assert.equal(filterRoot.querySelector('[data-id="activity-agent-read"]'),null,'Hidden credential must disappear immediately even when expanded');
 await new Promise(resolve=>setImmediate(resolve));
 assert.ok(lastFilter.exclude_token_ids.includes('agent'));assert.ok(filterRoot.querySelector('[data-id="activity-phone-read"]'));
 assert.equal(filterRoot.querySelector('[data-credential-choice="agent"]').checked,false);
 filterRoot.querySelector('[data-show-credentials]').click();await new Promise(resolve=>setImmediate(resolve));
 assert.ok(filterRoot.querySelector('[data-id="activity-agent-read"]'));
 assert.equal(filterRoot.querySelector('[data-credential-choice="agent"]').checked,true);
 filterCard.disconnectedCallback();
 console.log('Python-to-DOM related activity contract passed: live row IDs, action, baseline, connection, stale filters and explicit missing-ID/version diagnostics');
})().catch(error=>{console.error(error);process.exitCode=1;});
