"""Constants for HA Security."""

DOMAIN = "ha_security"
DEFAULT_SCAN_INTERVAL = 300
CONF_SCAN_INTERVAL = "scan_interval"
CONF_RETENTION_DAYS = "retention_days"
CONF_RECENT_MINUTES = "recent_minutes"
CONF_EXPOSE_NETWORK = "expose_network"
DEFAULT_RETENTION_DAYS = 30
DEFAULT_RECENT_MINUTES = 15
AUDIT_LIMIT = 10000
